---
- hosts: localhost
  connection: local  
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Test web1
      uri:
        url: http://192.168.33.10:8888
    - name: Test web2
      uri:
        url: http://192.168.33.10:8889
    - name : Test the loadbalancer
      uri:
        url: http://192.168.33.10:8080